
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const WEB3_CONNECT = 'WEB3_CONNECT';
export const WEB3_CONNECT_SUCCESS = 'WEB3_CONNECT_SUCCESS';
export const INIT_CONTRACT = 'INIT_CONTRACT';
export const INIT_CONTRACT_SUCCESS = 'INIT_CONTRACT_SUCCESS';
export const SEND_COIN = 'SEND_COIN';
export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';